### ISSUE TITLE
argument 'epochs' is missing in your implementation

### ISSUE THREAD

**Issue by d1024choi** [xupei0610/SocialVAE#3]
Hi. I am trying to reproduce your results by simply running the script that you recommend  
$ python main.py --train data/eth/train --test data/eth/test --ckpt log_eth --config config/eth.py

However, I got the following error message
>>Traceback (most recent call last):
>>  File "/home/dooseop/Pytorch/TrajectoryForecasting/03_Pedestrian/SocialVAE/main.py", line 162, in <module>
>>    end_epoch = start_epoch+1 if train_data is None or start_epoch >= settings.epochs else settings.epochs
>>AttributeError: 'Namespace' object has no attribute 'epochs'

It seems that the error occurs because 'epochs' doesn't exist in your argument definition in main.py. 
Do I miss something?

Thank you for your code sharing :)

**Comment by xupei0610** [comment]
Sorry that there were some code problems that was caused by the unmatched version number between our internal, testing code and the published one.

We just updated the main implementation code and also the model implementation. 

Please let me know if there are still problems to run the code. Thanks.
